import { VIEWPORT_LIMITS } from '../types/viewport';

export const CANVAS_CONSTANTS = {
  DEFAULT_WIDTH: 20,
  DEFAULT_HEIGHT: 20,
  MIN_CELL_SIZE: VIEWPORT_LIMITS.MIN_CELL_SIZE,
  MAX_CELL_SIZE: VIEWPORT_LIMITS.MAX_CELL_SIZE,
  DEFAULT_CELL_SIZE: VIEWPORT_LIMITS.DEFAULT_CELL_SIZE,
  NUMBER_AREA_WIDTH: 30,
  HIT_TOLERANCE: 0.25,
  GRID_COLOR: '#E0E0E0',
  MAJOR_GRID_COLOR: '#BDBDBD',
  MAJOR_GRID_INTERVAL: 10,
  USER_LINE_WIDTH: 2,
  GRID_LINE_WIDTH: 1,
  MAJOR_GRID_LINE_WIDTH: 1.5,
} as const;
